input_dir: "/resnick/groups/carnegie_poc/mcfallngai-lab/dhonson/dataAnalysis/20260118_chipSeqRep4/fqSymLinks/merge"

output_dir: "/resnick/groups/carnegie_poc/mcfallngai-lab/dhonson/dataAnalysis/20260118_chipSeqRep4/results"

bwa2_index: "/resnick/groups/carnegie_poc/mcfallngai-lab/dhonson/genomes/escolopes_v2/bwamem2/escolopes_v2"

blacklist: "/resnick/groups/carnegie_poc/mcfallngai-lab/dhonson/genomes/escolopes_v2/fastaRename/escolopes_v2simple.N10.blacklist.bed"

binsizes: [100, 1000]

effective_genome_size: 3199935799
min_length: 500
max_gap: 200

# Effective genome sizes of E. scolopes v2 for different read lengths
# Calculated using khmer unique-kmers.py 
# 
# 50nt  - 3050344950
# 75nt  - 3157233796
# 100nt - 3199935799
# 150nt - 3302373195
# 200nt - 3366959930
